### ISSUE TITLE
[EPIC] Tileset variations

### ISSUE THREAD

**Issue by raphmoreno** [raphmoreno/tab2trees#1]
# Description 

This EPIC is about creating the variations of tileset to make the forest more realistic and interesting 

It's mostly about creating the designs + 1 client implementation to fetch the right designs

### Types of forest tiles

- [ ]  "Naked" forest tile 
- [ ]  One tree forest tile 
- [ ]  Two-tree forest tile 
- [ ]  Three trees forest tile

### Types of trees 

- [ ] Pine tree 
- [ ] Oak 
- [ ] Cedar
- [ ] Willow 

### Client logic 

- [ ] Implement SVG insertion of trees into naked tiles 
- [ ] Implement logic for tree-type selection based on tree size and tile type
